---
name: Unit - BATS
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  unit:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        submodules: true

    - name: Setup BATS
      shell: bash
      run: |
        git clone --depth 1 --branch v1.2.1 https://github.com/bats-core/bats-core.git /tmp/bats-core
        sudo /tmp/bats-core/install.sh /usr/local

    - name: Checkout shdoc
      uses: actions/checkout@v4
      with:
        path: shdoc
        repository: reconquest/shdoc
        submodules: recursive

    - name: Setup requirements
      shell: bash
      run: |
        sudo curl -Lo /usr/local/bin/ec2-metadata-mock https://github.com/aws/amazon-ec2-metadata-mock/releases/download/v1.13.0/ec2-metadata-mock-`uname | tr '[:upper:]' '[:lower:]'`-amd64
        sudo chmod a+x /usr/local/bin/ec2-metadata-mock
        cd shdoc
        sudo make install
        cd ..
        sudo rm -rf shdoc vendor || echo "DONE"


    - name: Test
      shell: bash
      run: |
        echo "Test: test/requirements.bats"
        bats test/requirements.bats
        for f in $(ls test/*.bats | grep -v requirements); do
          echo "TEST: $f" && bats $f
          RET=$?
          [[ "${RET}" -eq 0 ]] && sleep 1 && echo ""
          [[ "${RET}" -ne 0 ]] && exit 1
        done
        exit "${RET}"
