---
name: Generate shell script docs
on:
  - pull_request

jobs:
  shdoc:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Checkout shdoc
      uses: actions/checkout@v2
      with:
        path: shdoc
        repository: reconquest/shdoc
        submodules: recursive

    - name: Setup shdoc
      shell: bash
      run: |
        cd shdoc
        sudo make install
        cd ..
        rm -rf shdoc

    - name: Render shdoc
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        for FILE in $(find . -type f -iname "*.sh" | grep -v test | sed 's/\.\///')
        do
          BAREFILE="${FILE##*/}"
          shdoc < ${FILE} > docs/${BAREFILE:0:-3}.md
        done
        git diff-index --quiet HEAD
        echo "git diff-index --quiet HEAD: $?"
        git status
        git config user.email github-actions@github.com
        git config user.name github-actions
        git commit -am "shdoc: Automated shell script document updates"
        git push