---
name: Shell script lint
on:
  - pull_request

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          submodules: true

      - name: Setup shellcheck
        shell: bash
        run: |
          sudo apt-get -y install shellcheck

      - name: shellcheck
        shell: bash
        run: |
          for f in "$(find . -iname "*.sh")"; do
            shellcheck $f
          done
